services:
  - type: web
    name: servidor-ia
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/.cache/huggingface